# 1. Conexión a SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=bd_clinica;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=SqlPassword2026!
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# 2. Configuración de Hibernate / JPA
# Esto creará las tablas automáticamente basadas en tus clases @Entity
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# 3. Evitar el error de Thymeleaf si los archivos están vacíos
spring.thymeleaf.cache=false

# 4. Configuración General
# ============================================
# CONFIGURACIÓN DE POWER BI
# ============================================
# URL Base del reporte publicado
powerbi.base.url=https://app.powerbi.com/view?r=eyJrIjoiNGIwYWE2MDAtYWQ1Mi00NzdlLWIzYmQtNzBiZWFmNmYwMjA4IiwidCI6ImM0YTY2YzM0LTJiYjctNDUxZi04YmUxLWIyYzI2YTQzMDE1OCIsImMiOjR9

# Nombres de las páginas en Power BI
powerbi.page.admin=Dashboard%20Administrador
powerbi.page.medico=Dashboard%20Medico
powerbi.page.paciente=Dashboard%20Paciente
powerbi.page.recepcion=Dashboard%20Recepcion

# Nombres de tablas para filtros
powerbi.filter.table.medicos=bd_clinica_medicos
powerbi.filter.table.pacientes=bd_clinica_pacientes

# 5. Configuración de APIPERU.DEV / APIS.NET.PE
apiperu.token=sk_16049.rVmdOdJ6y8IHLNIEnRy1XBpCRD1orep5
apiperu.base-url=https://api.apis.net.pe/v1

# 6. Configuración de CIE-11 (OMS)
icd.api.clientid=a45b6e4d-348c-4009-9dc9-8e3073ebfdba_6d0e41b5-1ac3-409d-ad68-b08b9772ba2f
icd.api.clientsecret=KCA3IpsG3yg9COOSTGjBu5gUt4h8tiqGckJg2qTFZ8A=
icd.api.tokenurl=https://icdaccessmanagement.who.int/connect/token

# 7. Configuracion de Correo Electronico (Gmail SMTP)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rhommelcrema@gmail.com
spring.mail.password= gvrd nagh xneb xmxq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
